"""Added the employee table

Revision ID: 011dbb4a1d98
Revises: 075f859c0212
Create Date: 2026-03-10 14:44:14.517456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '011dbb4a1d98'
down_revision: Union[str, Sequence[str], None] = '075f859c0212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employee_employee_id'), 'employee', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_employee_phone_number'), 'employee', ['employee_phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_employee_phone_number'), table_name='employee')
    op.drop_index(op.f('ix_employee_employee_id'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
