"""Updated the password field in the client table

Revision ID: 075f859c0212
Revises: 5b6a4b91568e
Create Date: 2026-03-04 12:09:06.491693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '075f859c0212'
down_revision: Union[str, Sequence[str], None] = '5b6a4b91568e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('national_id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_residence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('next_of_kin_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_of_kin_contact', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marital_status', sa.Enum('married', 'single', 'widowed', name='maritalstatus'), nullable=False),
    sa.Column('number_of_children', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_client_client_id'), 'client', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_client_phone_number'), 'client', ['client_phone_number'], unique=True)
    op.create_index(op.f('ix_client_national_id_number'), 'client', ['national_id_number'], unique=True)
    op.create_table('guarantor',
    sa.Column('guarantor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guarantor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('national_id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guarantor_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guarantor_business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guarantor_business_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('guarantor_id')
    )
    op.create_index(op.f('ix_guarantor_guarantor_id'), 'guarantor', ['guarantor_id'], unique=False)
    op.create_index(op.f('ix_guarantor_guarantor_phone_number'), 'guarantor', ['guarantor_phone_number'], unique=True)
    op.create_index(op.f('ix_guarantor_national_id_number'), 'guarantor', ['national_id_number'], unique=True)
    op.create_table('guarantor_business_photos',
    sa.Column('image_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guarantor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guarantor_id'], ['guarantor.guarantor_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_guarantor_business_photos_image_id'), 'guarantor_business_photos', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guarantor_business_photos_image_id'), table_name='guarantor_business_photos')
    op.drop_table('guarantor_business_photos')
    op.drop_index(op.f('ix_guarantor_national_id_number'), table_name='guarantor')
    op.drop_index(op.f('ix_guarantor_guarantor_phone_number'), table_name='guarantor')
    op.drop_index(op.f('ix_guarantor_guarantor_id'), table_name='guarantor')
    op.drop_table('guarantor')
    op.drop_index(op.f('ix_client_national_id_number'), table_name='client')
    op.drop_index(op.f('ix_client_client_phone_number'), table_name='client')
    op.drop_index(op.f('ix_client_client_id'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
