"""Updated the employee table

Revision ID: d2b63fa34de5
Revises: 011dbb4a1d98
Create Date: 2026-03-10 15:17:40.184092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2b63fa34de5'
down_revision: Union[str, Sequence[str], None] = '011dbb4a1d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('employee_type', sa.Enum('admin', 'regular', name='employee_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'employee_type')
    # ### end Alembic commands ###
